"""empty message

Revision ID: fbbd4310be60
Revises: 88e331476be4
Create Date: 2021-04-08 01:24:42.490074

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbbd4310be60'
down_revision = '88e331476be4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('mass', sa.Integer(), nullable=False),
    sa.Column('hair_color', sa.String(length=200), nullable=False),
    sa.Column('skin_color', sa.String(length=200), nullable=False),
    sa.Column('eye_color', sa.String(length=200), nullable=False),
    sa.Column('birth_year', sa.String(length=200), nullable=False),
    sa.Column('gender', sa.String(length=200), nullable=False),
    sa.Column('homeworld', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('rotation_period', sa.Integer(), nullable=False),
    sa.Column('orbital_period', sa.Integer(), nullable=False),
    sa.Column('diameter', sa.Integer(), nullable=False),
    sa.Column('climate', sa.String(length=200), nullable=False),
    sa.Column('gravity', sa.String(length=200), nullable=False),
    sa.Column('terrain', sa.String(length=200), nullable=False),
    sa.Column('surface_water', sa.Integer(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('species',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('classification', sa.String(length=200), nullable=False),
    sa.Column('designation', sa.String(length=200), nullable=False),
    sa.Column('average_height', sa.Integer(), nullable=False),
    sa.Column('skin_colors', sa.String(length=200), nullable=False),
    sa.Column('hair_colors', sa.String(length=200), nullable=False),
    sa.Column('eye_colors', sa.String(length=200), nullable=False),
    sa.Column('average_lifespan', sa.Integer(), nullable=False),
    sa.Column('homeworld', sa.String(length=200), nullable=False),
    sa.Column('language', sa.String(length=200), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('starships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('model', sa.String(length=200), nullable=False),
    sa.Column('manufacturer', sa.String(length=200), nullable=False),
    sa.Column('cost_in_credits', sa.Float(), nullable=False),
    sa.Column('length', sa.Float(), nullable=False),
    sa.Column('max_atmosphering_speed', sa.String(length=200), nullable=False),
    sa.Column('crew', sa.Float(), nullable=False),
    sa.Column('passengers', sa.Integer(), nullable=False),
    sa.Column('cargo_capacity', sa.Float(), nullable=False),
    sa.Column('consumables', sa.String(length=200), nullable=False),
    sa.Column('hyperdrive_rating', sa.Float(), nullable=False),
    sa.Column('MGLT', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites',
    sa.Column('favoriteid', sa.Integer(), nullable=False),
    sa.Column('userID', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], ),
    sa.PrimaryKeyConstraint('favoriteid')
    )
    op.drop_table('Starships')
    op.drop_table('Species')
    op.drop_table('Favorites')
    op.drop_table('Planets')
    op.drop_table('People')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('People',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('mass', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('hair_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('skin_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('eye_color', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('birth_year', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('gender', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('homeworld', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Planets',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('rotation_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('orbital_period', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('diameter', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('climate', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('gravity', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('terrain', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('surface_water', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('population', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Favorites',
    sa.Column('favoriteid', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('userID', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', mysql.VARCHAR(length=15), nullable=False),
    sa.ForeignKeyConstraint(['userID'], ['user.id'], name='Favorites_ibfk_1'),
    sa.PrimaryKeyConstraint('favoriteid'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Species',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('classification', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('designation', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('average_height', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skin_colors', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hair_colors', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('eye_colors', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('average_lifespan', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('homeworld', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('language', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('Starships',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('model', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('manufacturer', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('cost_in_credits', mysql.FLOAT(), nullable=False),
    sa.Column('length', mysql.FLOAT(), nullable=False),
    sa.Column('max_atmosphering_speed', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('crew', mysql.FLOAT(), nullable=False),
    sa.Column('passengers', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('cargo_capacity', mysql.FLOAT(), nullable=False),
    sa.Column('consumables', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('hyperdrive_rating', mysql.FLOAT(), nullable=False),
    sa.Column('MGLT', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('url', mysql.VARCHAR(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('favorites')
    op.drop_table('starships')
    op.drop_table('species')
    op.drop_table('planets')
    op.drop_table('people')
    # ### end Alembic commands ###
